doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        types:
            # Common
            datetime: App\Common\Infrastructure\Doctrine\Type\DateTimeType
            firstname: App\Common\Infrastructure\Doctrine\Type\FirstNameType
            lastname: App\Common\Infrastructure\Doctrine\Type\LastNameType
            email: App\Common\Infrastructure\Doctrine\Type\EmailType
            money: App\Common\Infrastructure\Doctrine\Type\MoneyType

            # Authentication
            username: App\Authentication\Infrastructure\Doctrine\Type\UsernameType
            hashed_password: App\Authentication\Infrastructure\Doctrine\Type\HashedPasswordType

            # User
            user_id: App\User\Infrastructure\Doctrine\Type\UserIdType
            user_status: App\User\Infrastructure\Doctrine\Type\UserStatusType

            # Product
            product_id: App\Product\Infrastructure\Doctrine\Type\ProductIdType
            product_name: App\Product\Infrastructure\Doctrine\Type\ProductNameType
            product_description: App\Product\Infrastructure\Doctrine\Type\ProductDescriptionType
            stock: App\Product\Infrastructure\Doctrine\Type\StockType

            # Order
            order_id: App\Order\Infrastructure\Doctrine\Type\OrderIdType
            order_item_id: App\Order\Infrastructure\Doctrine\Type\OrderItemIdType
            order_status: App\Order\Infrastructure\Doctrine\Type\OrderStatusType
            quantity: App\Order\Infrastructure\Doctrine\Type\QuantityType

            # Messaging
            conversation_id: App\Messaging\Infrastructure\Doctrine\Type\ConversationIdType
            participant_id: App\Messaging\Infrastructure\Doctrine\Type\ParticipantIdType
            participant_name: App\Messaging\Infrastructure\Doctrine\Type\ParticipantNameType
            message_id: App\Messaging\Infrastructure\Doctrine\Type\MessageIdType
            message_content: App\Messaging\Infrastructure\Doctrine\Type\MessageContentType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Authentication:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Authentication/Infrastructure/Doctrine/Mapping'
                prefix: 'App\Authentication\Domain\Entity'

            User:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/User/Infrastructure/Doctrine/Mapping'
                prefix: 'App\User\Domain\Entity'

            Messaging:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Messaging/Infrastructure/Doctrine/Mapping'
                prefix: 'App\Messaging\Domain\Entity'

            Product:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Product/Infrastructure/Doctrine/Mapping'
                prefix: 'App\Product\Domain\Entity'

            Order:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Order/Infrastructure/Doctrine/Mapping'
                prefix: 'App\Order\Domain\Entity'
