version: '3.8'

services:
    php:
        container_name: ${DOCKER_APP_NAME}_php
        build:
            context: ./.docker/php
        ports:
            - ${DOCKER_PHP_PORT}:9000
        working_dir: /var/www/
        volumes:
            - ./:/var/www/

    nginx:
        container_name: ${DOCKER_APP_NAME}_nginx
        image: nginx:stable-alpine
        ports:
            - ${DOCKER_NGINX_PORT}:80
        volumes:
            - ./:/var/www/
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    mysql:
        container_name: ${DOCKER_APP_NAME}_mysql
        image: mysql:5.7
        ports:
            - ${DOCKER_MYSQL_PORT}:3306
        volumes:
            - db_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}

    phpmyadmin:
        container_name: ${DOCKER_APP_NAME}_phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - ${DOCKER_PHPMYADMIN_PORT}:80

volumes:
    db_data: {}

