user_controller:
    resource: ../../src/User/UserInterface/Twig
    type: attribute

product_controller:
    resource: ../../src/Product/UserInterface/Twig
    type: attribute

order_controller:
    resource: ../../src/Order/UserInterface/Twig
    type: attribute

vue_controller:
    resource: ../../src/User/UserInterface/Vue
    type: attribute
