services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            'string $jwtPrivateKey': '%env(resolve:JWT_PRIVATE_KEY)%'
            'string $jwtPublicKey': '%env(resolve:JWT_PUBLIC_KEY)%'

    _instanceof:
        ######
        # Messenger handlers
        ################################
        App\Common\Application\Query\QueryHandler:
            tags:
                - { name: 'messenger.message_handler', bus: 'query.bus' }

        App\Common\Application\Command\CommandHandler:
            tags:
                - { name: 'messenger.message_handler', bus: 'command.bus' }

    ######
    # Common
    ################################
    App\Common\:
        resource: '%kernel.project_dir%/src/Common/'
        exclude:
            - '%kernel.project_dir%/src/Common/Infrastructure/Symfony/Kernel.php'

    ######
    # Authentication
    ################################
    App\Authentication\:
        resource: '%kernel.project_dir%/src/Authentication/'

    ######
    # User
    ################################
    App\User\:
        resource: '%kernel.project_dir%/src/User/'

    App\User\UserInterface\Twig\:
        resource: '../src/User/UserInterface/Twig'
        tags: [ 'controller.service_arguments' ]

    App\User\UserInterface\Vue\:
        resource: '../src/User/UserInterface/Vue'
        tags: [ 'controller.service_arguments' ]

    ######
    # Messaging
    ################################
    App\Messaging\:
        resource: '%kernel.project_dir%/src/Messaging/'
